"""Incident Report Exporter Component.

Generates 1-click downloadable executive debriefing summaries in Markdown, CSV, and JSON
for the active historical window, including predictions, unscaled units, and attribution proofs.
"""
from typing import Dict, Any
import json
import streamlit as st
import pandas as pd
import numpy as np

from src.config import Config


def generate_markdown_report(
    timestamp_str: str,
    tri_score: float,
    pred_risks: np.ndarray,
    raw_risks: Dict[str, float],
    narrative: str,
    upstream_share_val: float
) -> str:
    """Format an incident debrief in clean Markdown."""
    report = f"""# SupplyGuard Executive Disruption Incident Report
**Generated Timestamp:** {timestamp_str}  
**Overall System Total Risk Index (TRI):** {tri_score:.3f}  
**Upstream Shock Propagation Share:** {upstream_share_val:.1%}  

---

## 1. Echelon Risk Breakdown
| Echelon | Normalized Risk [0-1] | Raw Metric | Severity Tier |
|---|:---:|:---:|:---:|
| **Supplier** | {pred_risks[0]:.3f} | {raw_risks.get('Supplier', 0.0):.2f} RI | {'HIGH' if pred_risks[0] > 0.65 else ('MEDIUM' if pred_risks[0] >= 0.35 else 'LOW')} |
| **Manufacturer** | {pred_risks[1]:.3f} | {raw_risks.get('Manufacturer', 0.0):.2f} RI | {'HIGH' if pred_risks[1] > 0.65 else ('MEDIUM' if pred_risks[1] >= 0.35 else 'LOW')} |
| **Distributor** | {pred_risks[2]:.3f} | {raw_risks.get('Distributor', 0.0):.2f} RI | {'HIGH' if pred_risks[2] > 0.65 else ('MEDIUM' if pred_risks[2] >= 0.35 else 'LOW')} |
| **Retailer** | {pred_risks[3]:.3f} | {raw_risks.get('Retailer', 0.0):.2f} RI | {'HIGH' if pred_risks[3] > 0.65 else ('MEDIUM' if pred_risks[3] >= 0.35 else 'LOW')} |

---

## 2. Integrated Gradients Operational Narrative
> "{narrative}"

---

## 3. Prescriptive Operational Actions
- **Supplier Action:** Monitor lead times; activate backup vendor buffer stock.
- **Logistics Action:** Alert 3PL freight carriers; verify warehouse dwell times.
- **Retail Inventory:** Adjust safety stock algorithms to prevent stockouts.

*Generated by SupplyGuard Decision Support System.*
"""
    return report


def render_report_exporter(
    timestamp_str: str,
    tri_score: float,
    pred_risks: np.ndarray,
    raw_risks: Dict[str, float],
    narrative: str,
    upstream_share_val: float
):
    """Render download buttons for executive reports."""
    st.markdown("### 📄 Export Executive Incident Report")
    st.markdown("Download a formal incident debriefing report for this historical time window:")

    md_content = generate_markdown_report(
        timestamp_str, tri_score, pred_risks, raw_risks, narrative, upstream_share_val
    )

    # Prepare CSV data
    csv_df = pd.DataFrame([
        {"Echelon": name, "Normalized_Risk": float(pred_risks[i]), "Raw_Unit": raw_risks.get(name, 0.0), "Tier": 'HIGH' if pred_risks[i] > 0.65 else ('MEDIUM' if pred_risks[i] >= 0.35 else 'LOW')}
        for i, name in enumerate(Config.NODE_NAMES)
    ])
    csv_data = csv_df.to_csv(index=False)

    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            label="📥 Download Markdown Executive Summary",
            data=md_content,
            file_name=f"SupplyGuard_Report_{timestamp_str.replace(' ', '_').replace(':', '-')}.md",
            mime="text/markdown",
            use_container_width=True
        )

    with col2:
        st.download_button(
            label="📥 Download CSV Tabular Metrics",
            data=csv_data,
            file_name=f"SupplyGuard_Metrics_{timestamp_str.replace(' ', '_').replace(':', '-')}.csv",
            mime="text/csv",
            use_container_width=True
        )
